[export]
album = [ "Een Eeuw Eefde",]
convert_to_jpeg = true
description_template = "{descr}"
download_missing = true
edited_suffix = ""
exiftool = true
filename_template = "{created.date}T{created.hour}-{created.min}-{uuid[0,|1,|2,|3,|4,|5,|6,|7,|8,|9,|-,|D,|E,|F,]}"
ignore_date_modified = true
jpeg_ext = "jpg"
jpeg_quality = 0.8
original_suffix = ""
report = 'flickr.csv'
skip_original_if_edited = true
finder_tag_keywords = true
xattr_template = [ [ "authors", "Dirk Roorda",], [ "copyright", "https://erfgoedcentrumzutphen.nl/onderzoeken/beeldbank: zoek op Eefde",], [ "findercomment", "{descr}",],]
cleanup = true
update = true
overwrite = false
